[project]
name = "beam-dump"
version = "0.1.0"
description = "Mock controls of proton beam"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyepics>=3.5.9",
    "raylib>=5.5.0.4",
]
